[tool.poetry.dependencies]
python = "^3.9"
streamlit = "*"
openai = "*"
crewai = "*"
python-dotenv = "*"
sentence-transformers = "*"
bert-score = "*"
scikit-learn = "*"
pysqlite3-binary = "*"
altair = "*"
